config/routes.rb
Rails.application.routes.draw do

    # 404/500 pages
    get 'errors/not_found'
    get 'errors/internal_server_error'
    match "/404", to: "errors#not_found", via: :all
    match "/500", to: "errors#internal_server_error", via: :all
  
  #devise_scope :admins do
  #  # Redirests signing out users back to sign-in
  #  get "admins", to: "devise/sessions#new"
  #end

  devise_for :admins, controllers: { registrations: "registrations", sessions: "sessions" }
  #root "pages#home"
  root "pages#template_start"

  #post 'uploader/image', to: 'uploader#image' #add upload image to posts 
  #get 'blog', to: 'posts#index', as: :blog
  #resources :posts
  
  #resources :discover_flights
  #resources :messages
  #resources :enrollments
  #resources :book_downloads
  #resources :checkouts
  #resources :quiz_results

  # Enrollment form
  #get 'enroll-at-simplifly', to: 'enrollments#new', as: :enroll
  #get 'enrollment-confirmation', to: 'enrollments#confirmation', as: :enroll_confirmation

  # Contact form
  #get 'contact', to: 'messages#new', as: :contact
  #get 'contact-confirmation', to: 'messages#confirmation', as: :contact_confirmation
  #get 'visit-simplifly', to: 'messages#location', as: :location
  #get 'instruct-at-simplifly', to: 'messages#cfi', as: :cfi

  # Book Download
  #get 'book-download-confirmation', to: 'book_downloads#confirmation', as: :book_download_confirmation

  # Discovery flight form
  #get 'discovery-flight', to: 'discover_flights#new', as: :discovery_flight
  #get 'discovery-flight-confirmation', to: 'discover_flights#confirmation', as: :discovery_confirmation

  # Check out form
  #get 'rental-checkout', to: 'checkouts#new', as: :rental_checkout
  #get 'rental-checkout-confirmation', to: 'checkouts#confirmation', as: :checkout_confirmation

  # Quiz form
  #get 'quiz', to: 'quiz_results#new', as: :quiz
  #get 'quiz-confirmation', to: 'quiz_results#confirmation', as: :quiz_confirmation

  # Static Pages
  #get 'stratus-finance', to: 'pages#stratus', as: :stratus
  #get 'meritize', to: 'pages#meritize', as: :meritize
  #get 'accelerated-pilot-training', to: 'pages#accelerated', as: :accelerated
  #get 'flexible-pilot-training', to: 'pages#flexible', as: :flexible
  #get 'why-simplifly', to: 'pages#why_simplifly', as: :why_simplifly
  #get 'financing', to: 'pages#financing', as: :financing
  #get 'pilot-training-pricing-calculator', to: 'pages#cost' 
  #get 'approximate-pilot-training-costs', to: 'pages#cost', as: :cost
  #get 'timeline-to-be-a-pilot', to: 'pages#timeline', as: :timeline
  #get 'multi-engine-rating', to: 'pages#multi', as: :multi
  #get 'commercial-pilot-training', to: 'pages#commercial', as: :commercial
  #get 'instrument-rating', to: 'pages#instrument', as: :instrument
  #get 'private-pilot-training', to: 'pages#private_pilot', as: :private_pilot
  #get 'pilot-training', to: 'pages#pilot_training', as: :pilot_training
  #get 'airline-pilot-courses', to: 'pages#airline_pilot_courses', as: :airline_pilot_courses
  #get 'pilot-programs', to: 'pages#pilot_programs', as: :programs
  #get 'our-team', to: 'pages#our_team', as: :our_team
  #get 'terms-of-service-privacy-policy', to: 'pages#tos', as: :tos
  #get 'aircraft-rental', to: 'pages#aircraft_rental', as: :aircraft_rental
  #get 'fixed-wing-airplane-fleet', to: 'pages#fixed_wing', as: :fixed_wing
  #get 'rotary-wing-helicopter-fleet', to: 'pages#rotary_wing', as: :rotary_wing
  #get 'airplane-pilot-training', to: 'pages#airplane_training', as: :airplane_training
  #get 'helicopter-pilot-training', to: 'pages#helicopter_training', as: :helicopter_training
  #get 'about-ideal-aviation', to: 'pages#about_us', as: :about_us
  #get 'advanced_training', to: 'pages#advanced_training', as: :advanced_training
  #get 'pilot-resources', to: 'pages#pilot_resources', as: :pilot_resources
  #get 'careers', to: 'pages#careers', as: :careers
  

  # Previous Site's Routes
  #get 'home/flight-training', to: 'pages#why_simplifly'
  #get 'program-pricing', to: 'pages#cost'
  #get 'programs', to: 'pages#pilot_training'
  #get 'book-a-flight', to: 'discover_flights#new'
  #get 'locations', to: 'messages#location'
  #get 'contact-us', to: 'messages#new'
  #get 'simplifying-your-training', to: 'pages#why_simplifly'
  #get 'flight-instructors', to: 'pages#our_team'
  #get 'category/pilot', to: 'pages#airline_pilot_courses'
  #get 'becoming-a-pilot-timeline', to: 'pages#timeline'
  #get 'private-pilots-license', to: 'pages#private_pilot'
end

app/models/post.rb
class Post < ApplicationRecord
  
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  
  #validates :feature_image, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg', 'image/webp'], size_range: 1..(2.megabytes) }
  
  has_one_attached :feature_image

  validates :title, presence: true
  validates :post_date, presence: true
  validates :author, presence: true
  validates :meta_desription, presence: true


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_admin!, except: [:index, :show]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @posts = Post.friendly.find(params[:id])
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :post_date, :author, :post_content, :category, :meta_desription, :meta_keywords, :status, :feature_image)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= tinymce_assets %>

<%= form_with(model: post, class: "contents") do |form| %>
  <% if post.errors.any? %>
    <div class="px-10 lg:pl-20 lg:pr-20 pb-10" >
      <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
        <h2><%= pluralize(post.errors.count, "mistake") %>.  Cannot save. Please Fix.</h2>

        <ul>
          <% post.errors.each do |error| %>
            <li class="list-disc ml-5"><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <% if current_page?(new_post_path) %>
    <h1 class="font-bold text-4xl lg:pl-20 lg:text-left text-center">New Post</h1>
  <% else %>
    <h1 class="font-bold text-4xl lg:pl-20 lg:text-left text-center">Edit Post</h1>
  <% end %>

  <div class="flex flex-col lg:flex-row lg:px-10">
    <div class="px-10 lg:w-1/3 pr-10">
      <!--Blog Data-->
      <div class="my-5">
        <%= form.select(:status, ['Post Status','Published','Drafting'],  {}, {:class => 'block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full'}) %>
      </div>

      <div class="my-5">
        <%= form.select(:category, ['Category', 'News','Pilot Resources'],  {}, {:class => 'block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full'}) %>
      </div>

      <div class="my-5">
        <%= form.text_field :title, placeholder: "Post Title", class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
      </div>

      <div class="my-5">
        <%= form.date_field :post_date, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
      </div>

      <div class="my-5">
        <%= form.text_field :author, placeholder: "Author", class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
      </div> 

      <div class="my-5"> <%# Oops, I spelled description wrong.%>
        <%= form.text_area :meta_desription, rows: 3, placeholder: "Meta Description", class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
      </div>

      <div class="my-5">
        <%= form.text_field :meta_keywords, placeholder: "Meta Keywords", class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
      </div>

      <div class="my-5">
        <%= form.file_field :feature_image, class: "text-sm text-grey-500
            file:py-2 file:px-6
            file:rounded-lg file:border-0
            file:text-sm file:font-medium
            file:bg-blue-100 file:text-blue-700
            hover:file:cursor-pointer hover:file:bg-blue-200
            hover:file:text-blue-700" %>
      </div>

      <div class="inline">
        <%= form.submit class: "rounded-lg py-2 px-4 bg-blue-600 hover:bg-blue-800 text-sm text-white inline-block font-medium cursor-pointer", data: { turbo: false } %>
      </div>
    </div>
    <!--Blog editor-->
    <div class="lg:w-2/3 pt-10 lg:pt-0 lg:pl-5 lg:pr-10">
      <div class="lg:my-5">
        <%= form.text_area :post_content, rows: 30, class: "tinymce block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
        <%= tinymce %>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= post.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Post date:</strong>
    <%= post.post_date %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Author:</strong>
    <%= post.author %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Post content:</strong>
    <%= post.post_content %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Category:</strong>
    <%= post.category %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Meta description:</strong>
    <%= post.meta_desription %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Meta keywords:</strong>
    <%= post.meta_keywords %>
  </p>


  <% if action_name != "show" %>
    <%= link_to "Show this post", post, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this post', edit_post_path(post), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/posts/edit.html.erb
<%= render "shared/header" %>

<div class="pt-10 lg:py-10 bg-slate-100">

  <%= render "form", post: @post %>

  <%#= link_to 'Back to notams', notams_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

<%= render "shared/footer"%>

app/views/posts/index.html.erb
<%# Head / Meta Data %>
<% title("SimpliFly Blog - News and Pilot Training Resources") %>
<% meta_description("Explore the Simplifly blog for the latest insights and updates on pilot training in Mesa, Phoenix, Scottsdale, and Spanish Fork, Salt Lake. Stay informed and get inspired on your aviation journey.") %>
<% meta_keywords("Pilot Training Blog, Flight School Blog, Aviation News, Mesa Flight School, Phoenix Flight School, Scottsdale Flight School, Spanish Fork Flight School, Salt Lake Flight School") %>

<%= render "shared/header"%>

<div class="w-full bg-gradient-to-b from-slate-50 to-blue-100 h-max">
  <div class="containr px-6 mx-auto">

    <!-- Section: Design Block -->
    <section class="mb-32 text-gray-800 pt-12 lg:pt-24 text-center md:text-left">

      <h2 class="text-3xl font-bold mb-12 text-center">Latest articles</h2>

      <% @posts.sort_by(&:post_date).reverse_each do |post| %> 
        
          <div class="flex flex-wrap mb-6">
            <div class="grow-0 shrink-0 basis-auto w-full md:w-3/12 px-3 mb-6 md:mb-0 ml-auto">
              <div
                class="relative overflow-hidden bg-no-repeat bg-cover ripple shadow-lg rounded-lg mb-6"
                data-mdb-ripple="true" data-mdb-ripple-color="light">
                <% if post.feature_image.present?%>
                  <%= image_tag post.feature_image.url, class: "w-full max-h-48 object-cover", alt: "picture for article: #{post.title}"%>
                <%end%>
                <%= link_to post, class: "" do%>
                  <div class="absolute top-0 right-0 bottom-0 left-0 w-full h-full overflow-hidden bg-fixed opacity-0 hover:opacity-100 transition duration-300 ease-in-out"
                    style="background-color: rgba(251, 251, 251, 0.2)"></div>
                <%end%>
              </div>
            </div>

            
            <div class="grow-0 shrink-0 basis-auto w-full md:w-9/12 xl:w-7/12 px-3 mb-6 md:mb-0 mr-auto">
              <%= link_to post, class: "" do%>
              <h5 class="text-lg font-bold mb-3"><%=post.title%></h5>
              <div class="mb-3 text-ideal-blue font-medium text-sm flex items-center justify-center md:justify-start">
                <%= post.category %>
              </div>
              <p class="text-gray-500 mb-6">
                <small>Published <u><%= I18n.localize(post.post_date, :format => '%^b %-d %Y') %></u> by
                  <span href="" class="text-gray-900"><%= post.author%></span></small>
              </p>
              <p class="text-gray-500">
                <%= post.meta_desription%>
              </p>
              <%end%>
            </div>
          </div>
        
      <%end%>


    </section>
    <!-- Section: Design Block -->

  </div>
</div>
<%= render "shared/footer"%>

app/views/posts/new.html.erb
<%# Head / Meta Data %>
<%# title("Publish New NOTAM | Right Rudder Marketing Blog") %>
<%# meta_description("Publish a new NOTAM on the Right Rudder Marketing Blog") %>
<%# meta_keywords("aviation blog, flight school blog, aviation business blog, news about business aviation, flight school news") %>

<%= render "shared/header" %>

<div class="pt-10 lg:py-20 lg:pt-36 bg-slate-100">

  <%= render "form", post: @post %>

  <%#= link_to 'Back to notams', notams_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

<%= render "shared/footer"%>

app/views/posts/show.html.erb
<%# Head / Meta Data %>
<%# title(@post.title + " | Right Rudder Marketing Blog") %>
<%# meta_description(if @post.meta_description? then @post.meta_description end) %>
<%# meta_keywords(if @post.meta_keywords? then @post.meta_keywords end) %>
<%# og_image(@post.feature_image.url) %>
<%# twitter_image(@post.feature_image.url) %>

<%= render "shared/header" %>
<div class="text-lg bg-gradient-to-r from-slate-100 to-blue-100">
  

  <div class="flex flex-col items-center">
    <div class="lg:border-1 lg:w-3/5 flex flex-col lg:rounded-xl lg:my-10 border-slate-300 bg-slate-50">
      <!--Header-->
      <%#=image_tag @post.feature_image.url, class:"w-full object-cover object-center lg:rounded-t-xl", alt: "picture for article: #{@post.title}"%>
      <% if @post.feature_image.present?%>
      <%=image_tag @post.feature_image.url, class:"w-full object-cover object-center lg:rounded-t-xl", alt: "picture for article: #{@post.title}"%>
      <%end%>
      <!--Text-->
      <div class="">
        <div class="p-3">
          <h2 class="font-bold text-3xl"><%= @post.title %></h2>
          <div class="text-md font-semibold"><%= @post.category %></div>      
          <div class="text-sm font-semibold"><%= I18n.localize(@post.post_date, :format => '%^a %^b %-d %Y') %></div>
          <div class="text-sm italic">Published by <%= @post.author%></div>          
        </div>
        <%# Shown only when logged in %>
        <% if admin_signed_in? %>
        <hr class="border-slate-300">        
        <div class="p-3">
          <div>Status: <span class="italic"><%= @post.status %></span></div>
          <div class="flex flex-row gap-3">
            <%= link_to 'Edit this post', edit_post_path(@post), class: "font-semibold hover:underline", data: { turbo: false } %>
            <span class="hidden"> | </span>
            <%= button_to 'Delete this post', post_path(@post), method: :delete, class: " font-semibold hover:underline" %>
          </div>
        </div>
        <hr class="border-slate-300">
        <%end%>
      </div>
      
      <!--Content-->
      <div class="p-3 no-tailwindcss-base ">
        <%= raw @post.post_content %>
      </div>
    </div>
  </div>
</div>
<%#= render "shared/cta1" %>
<%= render "shared/cta_fly_with"%>
<%= render "shared/cta_next_steps"%>
<%= render "shared/footer" %>